# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x08pr.proto\x12\x11TestTask.Messages\"\x9c\x02\n\x0eWrapperMessage\x12\x36\n\rfast_response\x18\x01 \x01(\x0b\x32\x1f.TestTask.Messages.FastResponse\x12\x36\n\rslow_response\x18\x02 \x01(\x0b\x32\x1f.TestTask.Messages.SlowResponse\x12L\n\x19request_for_fast_response\x18\x03 \x01(\x0b\x32).TestTask.Messages.RequestForFastResponse\x12L\n\x19request_for_slow_response\x18\x04 \x01(\x0b\x32).TestTask.Messages.RequestForSlowResponse\")\n\x0c\x46\x61stResponse\x12\x19\n\x11\x63urrent_date_time\x18\x01 \x02(\t\".\n\x0cSlowResponse\x12\x1e\n\x16\x63onnected_client_count\x18\x01 \x02(\r\"\x18\n\x16RequestForFastResponse\":\n\x16RequestForSlowResponse\x12 \n\x18time_in_seconds_to_sleep\x18\x01 \x02(\r')

_WRAPPERMESSAGE = DESCRIPTOR.message_types_by_name['WrapperMessage']
_FASTRESPONSE = DESCRIPTOR.message_types_by_name['FastResponse']
_SLOWRESPONSE = DESCRIPTOR.message_types_by_name['SlowResponse']
_REQUESTFORFASTRESPONSE = DESCRIPTOR.message_types_by_name['RequestForFastResponse']
_REQUESTFORSLOWRESPONSE = DESCRIPTOR.message_types_by_name['RequestForSlowResponse']
WrapperMessage = _reflection.GeneratedProtocolMessageType('WrapperMessage', (_message.Message,), {
    'DESCRIPTOR': _WRAPPERMESSAGE,
    '__module__': 'pr_pb2'
    # @@protoc_insertion_point(class_scope:TestTask.Messages.WrapperMessage)
})
_sym_db.RegisterMessage(WrapperMessage)

FastResponse = _reflection.GeneratedProtocolMessageType('FastResponse', (_message.Message,), {
    'DESCRIPTOR': _FASTRESPONSE,
    '__module__': 'pr_pb2'
    # @@protoc_insertion_point(class_scope:TestTask.Messages.FastResponse)
})
_sym_db.RegisterMessage(FastResponse)

SlowResponse = _reflection.GeneratedProtocolMessageType('SlowResponse', (_message.Message,), {
    'DESCRIPTOR': _SLOWRESPONSE,
    '__module__': 'pr_pb2'
    # @@protoc_insertion_point(class_scope:TestTask.Messages.SlowResponse)
})
_sym_db.RegisterMessage(SlowResponse)

RequestForFastResponse = _reflection.GeneratedProtocolMessageType('RequestForFastResponse', (_message.Message,), {
    'DESCRIPTOR': _REQUESTFORFASTRESPONSE,
    '__module__': 'pr_pb2'
    # @@protoc_insertion_point(class_scope:TestTask.Messages.RequestForFastResponse)
})
_sym_db.RegisterMessage(RequestForFastResponse)

RequestForSlowResponse = _reflection.GeneratedProtocolMessageType('RequestForSlowResponse', (_message.Message,), {
    'DESCRIPTOR': _REQUESTFORSLOWRESPONSE,
    '__module__': 'pr_pb2'
    # @@protoc_insertion_point(class_scope:TestTask.Messages.RequestForSlowResponse)
})
_sym_db.RegisterMessage(RequestForSlowResponse)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _WRAPPERMESSAGE._serialized_start = 32
    _WRAPPERMESSAGE._serialized_end = 316
    _FASTRESPONSE._serialized_start = 318
    _FASTRESPONSE._serialized_end = 359
    _SLOWRESPONSE._serialized_start = 361
    _SLOWRESPONSE._serialized_end = 407
    _REQUESTFORFASTRESPONSE._serialized_start = 409
    _REQUESTFORFASTRESPONSE._serialized_end = 433
    _REQUESTFORSLOWRESPONSE._serialized_start = 435
    _REQUESTFORSLOWRESPONSE._serialized_end = 493
# @@protoc_insertion_point(module_scope)
