from PyQt5 import QtCore, QtGui, QtWidgets


class ClientUi:
    def setup_ui(self, client_window: QtWidgets.QMainWindow):
        self.centralWidget = QtWidgets.QWidget()

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        font = QtGui.QFont()
        font.setPointSize(12)


        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.connect_btn = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy.setHeightForWidth(self.connect_btn.sizePolicy().hasHeightForWidth())
        self.connect_btn.setSizePolicy(sizePolicy)
        self.connect_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.connect_btn.setMaximumHeight(40)
        self.connect_btn.setObjectName("connect_btn")
        self.gridLayout_2.addWidget(self.connect_btn, 8, 2, 1, 1)

        self.disconnect_btn = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy.setHeightForWidth(self.connect_btn.sizePolicy().hasHeightForWidth())
        self.disconnect_btn.setSizePolicy(sizePolicy)
        self.disconnect_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.disconnect_btn.setMaximumHeight(40)
        self.disconnect_btn.setObjectName("disconnect_btn")
        self.gridLayout_2.addWidget(self.disconnect_btn, 8, 2, 1, 1)
        self.disconnect_btn.setHidden(True)

        spacerItem = QtWidgets.QSpacerItem(33, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 6, 3, 1, 1)

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.reqtimeout_label = QtWidgets.QLabel(self.centralWidget)
        self.reqtimeout_label.setMaximumHeight(35)

        self.reqtimeout_label.setFont(font)
        self.reqtimeout_label.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.reqtimeout_label.setObjectName("reqtimeout_label")
        self.verticalLayout_3.addWidget(self.reqtimeout_label)

        self.request_timeout = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.request_timeout.sizePolicy().hasHeightForWidth())
        self.request_timeout.setSizePolicy(sizePolicy)
        self.request_timeout.setMinimumSize(QtCore.QSize(131, 22))
        self.request_timeout.setMaximumHeight(35)
        self.request_timeout.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.request_timeout.setPlaceholderText("seconds")
        self.request_timeout.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp("[1-9][0-9]*")))
        self.request_timeout.setObjectName("request_timeout")
        self.verticalLayout_3.addWidget(self.request_timeout)

        self.server_sleep_time = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy.setHeightForWidth(self.server_sleep_time.sizePolicy().hasHeightForWidth())
        self.server_sleep_time.setSizePolicy(sizePolicy)
        self.server_sleep_time.setMinimumSize(QtCore.QSize(131, 22))
        self.server_sleep_time.setMaximumHeight(35)
        self.server_sleep_time.setPlaceholderText("seconds")
        self.server_sleep_time.setObjectName("server_sleep_time")
        self.server_sleep_time.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp("[1-9][0-9]*")))
        self.server_sleep_time.setHidden(True)
        self.verticalLayout_3.addWidget(self.server_sleep_time)

        self.gridLayout_2.addLayout(self.verticalLayout_3, 5, 2, 1, 1)

        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")

        self.req_for_fast = QtWidgets.QRadioButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.req_for_fast.sizePolicy().hasHeightForWidth())
        self.req_for_fast.setSizePolicy(sizePolicy)
        self.req_for_fast.setMinimumSize(QtCore.QSize(172, 19))
        self.req_for_fast.setMaximumHeight(35)
        self.req_for_fast.setFont(font)
        self.req_for_fast.setObjectName("req_for_fast")

        self.req_for_slow = QtWidgets.QRadioButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.req_for_slow.sizePolicy().hasHeightForWidth())
        self.req_for_slow.setSizePolicy(sizePolicy)
        self.req_for_slow.setMinimumSize(QtCore.QSize(172, 19))
        self.req_for_slow.setMaximumHeight(35)
        self.req_for_slow.setFont(font)
        self.req_for_slow.setObjectName("req_for_slow")

        self.requests_group = QtWidgets.QButtonGroup(self.centralWidget)
        self.requests_group.setObjectName("requests_group")
        self.requests_group.addButton(self.req_for_fast)
        self.verticalLayout.addWidget(self.req_for_fast)
        self.requests_group.addButton(self.req_for_slow)
        self.verticalLayout.addWidget(self.req_for_slow)
        self.req_for_fast.setChecked(True)

        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 6, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 5, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 7, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(33, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 5, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem8, 4, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.ip_label = QtWidgets.QLabel(self.centralWidget)
        self.ip_label.setFont(font)
        self.ip_label.setObjectName("ip_label")
        self.horizontalLayout.addWidget(self.ip_label)

        self.ip = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip.sizePolicy().hasHeightForWidth())
        self.ip.setSizePolicy(sizePolicy)
        self.ip.setMinimumSize(QtCore.QSize(173, 22))
        self.ip.setMaximumHeight(35)
        octet = "[1-9]|[1-9][0-9]|[1][0-9]{1,2}|[2][0-4][0-9]|[2][5][0-5]"
        self.ip.setValidator(
            QtGui.QRegExpValidator(QtCore.QRegExp(f"({octet})\.({octet}|[0])\.({octet}|[0])\.({octet}|[0])")))
        self.ip.setObjectName("ip")

        self.horizontalLayout.addWidget(self.ip)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.port_label = QtWidgets.QLabel(self.centralWidget)
        self.port_label.setFont(font)
        self.port_label.setObjectName("port_label")
        self.horizontalLayout_2.addWidget(self.port_label)

        self.port = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port.sizePolicy().hasHeightForWidth())
        self.port.setSizePolicy(sizePolicy)
        self.port.setMinimumSize(QtCore.QSize(173, 22))
        self.port.setMaximumHeight(35)
        self.port.setPlaceholderText("5000")
        self.port.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp("[1-9][0-9]{3}")))
        self.port.setObjectName("port")
        self.horizontalLayout_2.addWidget(self.port)

        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 1, 2, 2)
        spacerItem9 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem10 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 0, 0, 1, 1)

        spacerItem11 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 0, 2, 1, 1)

        self.save_log_btn = QtWidgets.QPushButton(self.centralWidget)
        self.save_log_btn.setObjectName("save_log_btn")
        self.save_log_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.save_log_btn.setIcon(QtGui.QIcon("save.png"))

        self.gridLayout.addWidget(self.save_log_btn, 0, 3, 1, 1)

        self.log = QtWidgets.QTextBrowser(self.centralWidget)
        self.log.setMinimumSize(QtCore.QSize(471, 291))
        self.log.setObjectName("log")
        self.gridLayout.addWidget(self.log, 1, 0, 1, 4)

        self.gridLayout_2.addLayout(self.gridLayout, 0, 4, 10, 1)
        spacerItem12 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem13, 9, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.recontimeout_label = QtWidgets.QLabel(self.centralWidget)
        self.recontimeout_label.setMaximumHeight(35)
        self.recontimeout_label.setFont(font)
        self.recontimeout_label.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.recontimeout_label.setObjectName("recontimeout_label")
        self.verticalLayout_2.addWidget(self.recontimeout_label)

        self.log_label = QtWidgets.QLabel(self.centralWidget)
        font.setPointSize(11)
        self.log_label.setFont(font)
        self.log_label.setObjectName("log_label")
        self.gridLayout.addWidget(self.log_label, 0, 1, 1, 1)

        self.reconnection_timeout = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reconnection_timeout.sizePolicy().hasHeightForWidth())
        self.reconnection_timeout.setSizePolicy(sizePolicy)
        self.reconnection_timeout.setMinimumSize(QtCore.QSize(131, 21))
        self.reconnection_timeout.setMaximumHeight(35)
        self.reconnection_timeout.setText("")
        self.reconnection_timeout.setObjectName("reconnection_timeout")
        self.reconnection_timeout.setPlaceholderText("seconds")
        self.reconnection_timeout.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp("[1-9][0-9]*")))
        self.verticalLayout_2.addWidget(self.reconnection_timeout)

        self.gridLayout_2.addLayout(self.verticalLayout_2, 6, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 3, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem15, 2, 1, 1, 1)

        client_window.setCentralWidget(self.centralWidget)
        self.retranslate_ui(client_window)
        QtCore.QMetaObject.connectSlotsByName(client_window)

    def retranslate_ui(self, client_window):
        _translate = QtCore.QCoreApplication.translate

        client_window.setWindowTitle(_translate("Client", "Client"))
        self.connect_btn.setText(_translate("Client", "Connect"))
        self.connect_btn.setStyleSheet('background: rgb(222, 119, 58);')
        self.disconnect_btn.setText(_translate("Client", "Disconnect"))
        self.disconnect_btn.setStyleSheet('background: rgb(102, 0, 248);')
        self.reqtimeout_label.setText(_translate("Client", "Request timeout"))
        self.req_for_fast.setText(_translate("Client", "RequestForFastResponse"))
        self.req_for_slow.setText(_translate("Client", "RequestForSlowResponse"))
        self.ip_label.setText(_translate("Client", "IP"))
        self.port_label.setText(_translate("Client", "Port"))
        self.log_label.setText(_translate("Client", "Request log"))
        self.recontimeout_label.setText(_translate("Client", "Reconnection timeout"))
